import os
from typing import List

from dotenv import load_dotenv
from langchain_tavily import TavilySearch
from langchain_core.tools import tool


load_dotenv()

@tool
def today_date() -> str:
    """Returns today's date in ISO format (YYYY-MM-DD)."""
    from datetime import date
    return date.today().isoformat()


def tavily_search(query: str, max_results: int = 5) -> List[dict]:
    tool = TavilySearch(
        max_results=max_results,
        tavily_api_key=os.getenv("TAVILY_API_KEY"),
    )
    results = tool.invoke({"query": query})

    if isinstance(results, str):
        import json

        try:
            results = json.loads(results)
        except json.JSONDecodeError:
            results = []

    if isinstance(results, dict):
        results = results.get("results", results.get("data", []))

    normalized: List[dict] = []
    for r in results or []:
        if isinstance(r, str):
            continue
        normalized.append(
            {
                "title": r.get("title") or "",
                "url": r.get("url") or "",
                "snippet": r.get("content") or r.get("snippet") or "",
                "published_at": r.get("published_date") or r.get("published_at"),
                "source": r.get("source"),
            }
        )
    return normalized


def gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    resp = client.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )

    # Depending on SDK version, parts may hang off resp.candidates[0].content.parts
    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found in response.")



